[package]
name = "arkworks-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
ark-std = "0.4.0"
rand = "0.8"
hex = { version = "0.4", default-features = false, features = ["alloc"] }
